USE TESTBED
GO

BEGIN

SELECT COUNT(* ) AS [NUMBER OF ROWS] FROM TYPE4_STRING

--UPDATING DESCRIPTION
BEGIN
	UPDATE  TS4 
	SET TS4.DESCRIPTION = A_OUTER.DESCRIPTION
	FROM TYPE4_STRING TS4
	JOIN 
		(SELECT TS1.* FROM LANG TS1
		INNER JOIN 
				(
				SELECT L.STRING_ID,L.LANGUAGE_CODE,L.DESCRIPTION FROM TYPE4_STRING TS
				JOIN LANG L
				ON L.STRING_ID=TS.STRING_ID
				AND L.[ENGLISH TXT]=TS.DESCRIPTION
				)A
		ON A.STRING_ID=TS1.STRING_ID
		AND TS1.LANGUAGE_CODE=2025) A_OUTER
	ON A_OUTER.STRING_ID=TS4.STRING_ID
	AND A_OUTER.LANGUAGE_CODE = TS4.LANGUAGE_CODE
END

--INSERTING MISSING STRING_ID
BEGIN
	INSERT INTO TYPE4_STRING
	SELECT LA.STRING_ID,LA.LANGUAGE_CODE,LA.DESCRIPTION TYPE4_STRING FROM LANG LA
	LEFT JOIN TYPE4_STRING LT
	ON LT.STRING_ID=LA.STRING_ID
	WHERE LT.DESCRIPTION IS NULL
	UNION
	SELECT LA.STRING_ID,1033,LA.DESCRIPTION TYPE4_STRING FROM LANG LA
	LEFT JOIN TYPE4_STRING LT
	ON LT.STRING_ID=LA.STRING_ID
	WHERE LT.DESCRIPTION IS NULL
END
